apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x5iyjhmf8-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/x5iyjhmf8-java-quarkus-gitops